export const POSTS_ACTION_TYPES = {
  FETCH_POSTS_START: "posts/FETCH_POSTS_START",
  FETCH_POSTS_SUCCESS: "posts/FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAILED: "posts/FETCH_POSTS_FAILED",
  UNSUBSCRIBE_POSTS: "UNSUBSCRIBE_POSTS",
};
